### ISSUE TITLE
Song name parse error

### ISSUE THREAD

**Issue by Motyldrogi** [isladot/spotify-readme-widget#25]
Hey, when i play this song https://open.spotify.com/track/5TwgWjWPDj5Qs041ZssUAF?si=24a6a072f4164449 the widget somehow breaks. It is also not the only song where it happens. It's not that big of a problem, but if you have fun fixing it, it would be nice!

> This page contains the following errors:
error on line 35 at column 17: xmlParseEntityRef: no name
Below is a rendering of the page up to the first error.

**Comment by isladot** [comment]
Fixed! #50

The problem was the "&" tag, which by default is not correctly escaped by EJS.

It's been almost an year I know, I'm really sorry.
